### ISSUE TITLE
Update kotlin gradle plugin

### ISSUE THREAD

**Issue by kdgr** [vanlooverenkoen/flutter_appcenter_release_manager#35]
Hello, could you update kotlin gradle plugin version ?

> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
> The following dependencies do not satisfy the required version:
> project ':appcenter_release_manager' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by vanlooverenkoen** [comment]
Yes! Thanks for pointing out! I will fix it today and create a new release

**Comment by vanlooverenkoen** [comment]
3.0.0 is released
